import type { Classroom } from "@/types/classroom";

const MOCK_CLASSROOMS: Classroom[] = [
  {
    id: "1",
    name: "React Fundamentals",
    description: "Learn React basics and hooks",
    teacherId: "teacher-demo",
    teacherName: "Demo Teacher",
    joinCode: "DEMO01",
    members: ["teacher-demo", "st1", "st2"],
    userRole: "student",
    assignments: [
      {
        id: "a1",
        title: "Build a Todo App",
        dueDate: "2025-01-15",
        createdBy: "Teacher Name",
        description: "Create a functional todo app using React hooks",
        discussions: [
          {
            id: "d1",
            author: "Sarah",
            message: "How do I handle form state?",
            timestamp: "2 hours ago",
            replies: 2,
          },
          {
            id: "d2",
            author: "John",
            message: "Can we use Context API?",
            timestamp: "1 hour ago",
            replies: 1,
          },
        ],
        submissions: [
          {
            id: "s1",
            studentName: "Sarah",
            studentId: "st1",
            content: "I used useState for the todo list and input field",
            submittedAt: "2025-01-14",
            status: "graded",
            grade: 92,
            feedback: "Great implementation! Good use of hooks.",
          },
          {
            id: "s2",
            studentName: "John",
            studentId: "st2",
            content: "Implemented with Context API as suggested",
            submittedAt: "2025-01-13",
            status: "graded",
            grade: 95,
            feedback: "Excellent work! Clean code and great performance.",
          },
          {
            id: "s3",
            studentName: "Emma",
            studentId: "st3",
            content: "Used useReducer for complex state management",
            submittedAt: "2025-01-14",
            status: "submitted",
          },
        ],
      },
      {
        id: "a2",
        title: "Create a Counter Component",
        dueDate: "2025-01-22",
        createdBy: "Teacher Name",
        description:
          "Build a counter component with increment/decrement buttons",
        discussions: [
          {
            id: "d3",
            author: "Mike",
            message: "Should I use useState or useReducer?",
            timestamp: "30 mins ago",
            replies: 3,
          },
        ],
        submissions: [
          {
            id: "s4",
            studentName: "Mike",
            studentId: "st4",
            content: "Simple counter using useState hooks",
            submittedAt: "2025-01-21",
            status: "graded",
            grade: 88,
            feedback: "Good work, consider adding reset functionality.",
          },
          {
            id: "s5",
            studentName: "Lisa",
            studentId: "st5",
            content: "Counter with step increment feature",
            submittedAt: "2025-01-20",
            status: "graded",
            grade: 90,
            feedback: "Nice extra feature! Well done.",
          },
        ],
      },
    ],
    lectureNotes: [
      { id: "l1", title: "Introduction to JSX", date: "2025-01-08" },
      { id: "l2", title: "State and Props", date: "2025-01-10" },
    ],
    discussions: [
      {
        id: "d1",
        author: "Sarah",
        message: "How do I manage global state?",
        timestamp: "3 days ago",
        replies: 3,
      },
      {
        id: "d2",
        author: "John",
        message: "Best practices for hooks",
        timestamp: "2 days ago",
        replies: 5,
      },
    ],
  },
  {
    id: "2",
    name: "TypeScript Advanced",
    description: "Master advanced TypeScript patterns",
    teacherId: "teacher-demo",
    teacherName: "Demo Teacher",
    joinCode: "DEMO02",
    members: ["teacher-demo"],
    userRole: "teacher",
    assignments: [
      {
        id: "a3",
        title: "Generic Types Project",
        dueDate: "2025-01-20",
        createdBy: "Teacher Name",
        description: "Implement generic types for different data structures",
        discussions: [
          {
            id: "d4",
            author: "Lisa",
            message: "How do generics work with arrays?",
            timestamp: "1 day ago",
            replies: 2,
          },
        ],
        submissions: [
          {
            id: "s6",
            studentName: "Lisa",
            studentId: "st6",
            content: "Created generic Stack and Queue data structures",
            submittedAt: "2025-01-19",
            status: "graded",
            grade: 94,
            feedback: "Perfect implementation with proper type constraints!",
          },
          {
            id: "s7",
            studentName: "Alex",
            studentId: "st7",
            content: "Implemented generic Repository pattern",
            submittedAt: "2025-01-18",
            status: "submitted",
          },
        ],
      },
    ],
    lectureNotes: [
      { id: "l3", title: "Advanced Types", date: "2025-01-09" },
      { id: "l4", title: "Type Guards and Inference", date: "2025-01-11" },
    ],
    discussions: [
      {
        id: "d3",
        author: "Mike",
        message: "Utility types explanation",
        timestamp: "2 days ago",
        replies: 2,
      },
      {
        id: "d4",
        author: "Lisa",
        message: "Generics deep dive",
        timestamp: "1 day ago",
        replies: 4,
      },
    ],
  },
  {
    id: "3",
    name: "Next.js Full Stack",
    description: "Build full-stack applications with Next.js",
    teacherId: "teacher-demo",
    teacherName: "Demo Teacher",
    joinCode: "DEMO03",
    members: ["teacher-demo"],
    userRole: "teacher",
    assignments: [
      {
        id: "a5",
        title: "API Routes Project",
        dueDate: "2025-01-25",
        createdBy: "Teacher Name",
        description: "Build a full-stack API",
        discussions: [
          {
            id: "d5",
            author: "Alex",
            message: "Can we use middleware in routes?",
            timestamp: "12 hours ago",
            replies: 1,
          },
        ],
        submissions: [
          {
            id: "s8",
            studentName: "Alex",
            studentId: "st8",
            content: "Built REST API with CRUD operations",
            submittedAt: "2025-01-24",
            status: "graded",
            grade: 87,
            feedback: "Good API structure. Add error handling for edge cases.",
          },
          {
            id: "s9",
            studentName: "Chris",
            studentId: "st9",
            content: "Created API with middleware authentication",
            submittedAt: "2025-01-23",
            status: "submitted",
          },
        ],
      },
      {
        id: "a6",
        title: "Database Integration",
        dueDate: "2025-02-01",
        createdBy: "Teacher Name",
        description: "Integrate database with Next.js",
        discussions: [
          {
            id: "d6",
            author: "Emma",
            message: "Which ORM should I use?",
            timestamp: "8 hours ago",
            replies: 4,
          },
        ],
        submissions: [
          {
            id: "s10",
            studentName: "Emma",
            studentId: "st10",
            content: "Integrated Prisma ORM with Next.js",
            submittedAt: "2025-01-31",
            status: "submitted",
          },
        ],
      },
    ],
    lectureNotes: [
      { id: "l5", title: "App Router Basics", date: "2025-01-12" },
      { id: "l6", title: "Server Actions", date: "2025-01-14" },
    ],
    discussions: [
      {
        id: "d5",
        author: "Alex",
        message: "Deployment best practices",
        timestamp: "5 days ago",
        replies: 6,
      },
      {
        id: "d6",
        author: "Emma",
        message: "Performance optimization",
        timestamp: "3 days ago",
        replies: 3,
      },
    ],
  },
  {
    id: "4",
    name: "Web Design Principles",
    description: "Create beautiful and usable interfaces",
    teacherId: "teacher-demo",
    teacherName: "Demo Teacher",
    joinCode: "DEMO04",
    members: ["teacher-demo"],
    userRole: "teacher",
    assignments: [
      {
        id: "a7",
        title: "Design System Creation",
        dueDate: "2025-01-28",
        createdBy: "Teacher Name",
        description: "Create a design system",
        discussions: [
          {
            id: "d7",
            author: "Chris",
            message: "How to organize design tokens?",
            timestamp: "4 hours ago",
            replies: 2,
          },
        ],
        submissions: [
          {
            id: "s11",
            studentName: "Chris",
            studentId: "st11",
            content: "Created comprehensive design system with Figma",
            submittedAt: "2025-01-27",
            status: "graded",
            grade: 96,
            feedback: "Outstanding design system! Well organized and scalable.",
          },
          {
            id: "s12",
            studentName: "Diana",
            studentId: "st12",
            content: "Design tokens organized with CSS variables",
            submittedAt: "2025-01-26",
            status: "graded",
            grade: 91,
            feedback:
              "Great implementation. Consider adding dark mode variants.",
          },
        ],
      },
      {
        id: "a8",
        title: "Responsive Layout",
        dueDate: "2025-02-04",
        createdBy: "Teacher Name",
        description: "Build responsive layouts",
        discussions: [],
        submissions: [
          {
            id: "s13",
            studentName: "Diana",
            studentId: "st12",
            content: "Mobile-first responsive design with Tailwind",
            submittedAt: "2025-02-02",
            status: "submitted",
          },
        ],
      },
    ],
    lectureNotes: [
      { id: "l7", title: "Color Theory", date: "2025-01-13" },
      { id: "l8", title: "Typography Guidelines", date: "2025-01-15" },
    ],
    discussions: [
      {
        id: "d7",
        author: "Chris",
        message: "Accessibility tips",
        timestamp: "1 week ago",
        replies: 4,
      },
      {
        id: "d8",
        author: "Diana",
        message: "UI animation trends",
        timestamp: "5 days ago",
        replies: 2,
      },
    ],
  },
];

export default MOCK_CLASSROOMS;